### PR TITLE
Update anyway_config dependency

### PR DESCRIPTION
**Pull request by palkan**
anyway_config 2.0 is coming soon, no breaking changes for this lib.

See more in https://github.com/palkan/anyway_config/issues/32

### CODE REVIEW

**Comment by palkan** [comment]
@aderyabin ping)

**Comment by aderyabin** [comment]
👍

**Comment by palkan** [comment]
Thanks! Please, let me know when it gets released

**Comment by bibendi** [comment]
Hey!
Maybe it's time to release? :thinking: :santa:

**Pull request merged**
