### PR TITLE
Change try syntax for old ruby

### PR DESCRIPTION
**Pull request by dissident**
https://github.com/aderyabin/sniffer/issues/23

### CODE REVIEW

**Comment by aderyabin** [comment]
Hey, @dissident.
Thanks for PR. Could you please add ruby 2.2.2 to RVM block in `.travis.yml` file.

**Comment by dissident** [comment]
Forgot that this is not a rails and the method .try is not present. So I added patch for Object with .try method.

**Comment by aderyabin** [comment]
I don't like an idea of monkey-patching ruby core classes. Please rewrite without it.

**Comment by dissident** [comment]
If you don't like monkey-patching can you please explain to me what you want to receive then request or response don't have .to_h method?

**Comment by aderyabin** [comment]
It's easy. `Sniffer::DataItem` has to accessors – `request` and `response`. By default they are empty, so `#to_h` returns `nil`:
```
Sniffer::DataItem.new.to_h
=> {:request=>nil, :response=>nil}
```

At first version, you tried to use `#try` from `ActiveSupport`. 

A safe navigation operator (`.&`) came to us with ruby 2.3 ([link](https://www.ruby-lang.org/en/news/2015/12/25/ruby-2-3-0-released/)). So if you add support older versions you have to replace `Sniffer::DataItem#to_h` to:

```
def to_h
  {
    request: request && request.to_h,
    response: response && response.to_h
  }	  
end
```

**Comment by dissident** [comment]
Oh, response and request your own objects. I think it may be Typhoeus::Request, Net::HTTP::Response. It was easer.

**Comment by aderyabin** [comment]
Saving raw adapter requests and responses I plan to add in future versions.

**Comment by aderyabin** [comment]
Please squash all commits into one.

**Pull request merged**
